# Generated by Django 5.2.8 on 2025-11-19 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=20, unique=True)),
                ('menu_config', models.JSONField(default=dict)),
                ('theme_color', models.CharField(default='#25D366', max_length=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('bot_state', models.CharField(default='IDLE', max_length=50)),
                ('cart', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_address', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_proof_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nuevo'), ('WAITING_PAYMENT', 'Esperando Pago'), ('VERIFYING_PAYMENT', 'Verificando Comprobante'), ('CONFIRMED', 'Confirmado'), ('COMPLETED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.store')),
            ],
        ),
    ]
