# Generated by Django 5.2.8 on 2025-12-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_store_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/%d/', verbose_name='Comprobante de pago (imagen)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_proof_url',
            field=models.URLField(blank=True, null=True, verbose_name='Comprobante de pago (URL)'),
        ),
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('WOMPI', 'Wompi'), ('BOLD', 'Bold'), ('NEQUI_MANUAL', 'Nequi Manual (Foto Comprobante)')], default='NEQUI_MANUAL', max_length=20, verbose_name='Proveedor de Pago')),
                ('is_active', models.BooleanField(default=False, help_text='Si está inactivo, se usará método manual', verbose_name='Activo')),
                ('public_key', models.CharField(blank=True, help_text='Public key del proveedor de pagos', max_length=255, verbose_name='API Key Pública')),
                ('private_key', models.CharField(blank=True, help_text='Private key del proveedor de pagos', max_length=255, verbose_name='API Key Privada')),
                ('integrity_secret', models.CharField(blank=True, help_text='Usado para validar webhooks de Wompi', max_length=255, verbose_name='Secret de Integridad (Wompi)')),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret adicional para validar webhooks', max_length=255, verbose_name='Webhook Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='orders.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Configuración de Pago',
                'verbose_name_plural': 'Configuraciones de Pago',
            },
        ),
    ]
