# Generated by Django 5.2.9 on 2025-12-17 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(max_length=50, verbose_name='WhatsApp Business Account ID')),
                ('phone_number_id', models.CharField(db_index=True, max_length=50, verbose_name='Phone Number ID')),
                ('display_phone_number', models.CharField(max_length=20, verbose_name='Número de teléfono (display)')),
                ('encrypted_token', models.TextField(verbose_name='Token encriptado (SUAT)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de conexión')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_credentials', to='orders.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Credencial de WhatsApp',
                'verbose_name_plural': 'Credenciales de WhatsApp',
            },
        ),
    ]
