# Generated by Django 5.2.9 on 2025-12-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_whatsappcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram')], default='WHATSAPP', max_length=20, verbose_name='Fuente del pedido'),
        ),
    ]
