# Generated by Django 5.2.9 on 2025-12-22 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(db_index=True, max_length=50, verbose_name='ID del Canal')),
                ('channel_type', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram')], default='WHATSAPP', max_length=20, verbose_name='Tipo de Canal')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Total de pedidos')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total gastado')),
                ('last_order_at', models.DateTimeField(blank=True, null=True, verbose_name='Último pedido')),
                ('first_contact_at', models.DateTimeField(auto_now_add=True, verbose_name='Primer contacto')),
                ('favorite_products', models.JSONField(default=list, verbose_name='Productos favoritos')),
                ('notes', models.TextField(blank=True, help_text='Notas del restaurante sobre el cliente (alergias, preferencias, etc.)', verbose_name='Notas')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='orders.store')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-last_order_at', '-first_contact_at'],
                'unique_together': {('store', 'channel_id', 'channel_type')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.customer', verbose_name='Cliente'),
        ),
    ]
