# Generated by Django 5.2.8 on 2026-06-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_bot_token', models.TextField(verbose_name='Token del bot (encriptado)')),
                ('bot_username', models.CharField(blank=True, max_length=64, verbose_name='Username del bot (@...)')),
                ('webhook_secret', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Secreto de webhook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_credentials', to='orders.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Credencial de Telegram',
                'verbose_name_plural': 'Credenciales de Telegram',
            },
        ),
    ]
