# Generated by Django 5.2.8 on 2026-06-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_telegramcredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
