# Generated by Django 5.2.8 on 2026-06-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_store_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_winback_at',
            field=models.DateTimeField(blank=True, help_text='Evita re-contactar al mismo cliente repetidamente', null=True, verbose_name='Último mensaje de recompra'),
        ),
    ]
