# Generated by Django 5.2.8 on 2026-06-10 03:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_customer_last_winback_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('price_cop', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio mensual (COP)')),
                ('conversation_limit', models.PositiveIntegerField(blank=True, help_text='NULL = ilimitado', null=True, verbose_name='Conversaciones/mes')),
                ('features', models.JSONField(blank=True, default=list, help_text='Lista de strings para mostrar en el paywall', verbose_name='Características')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='last_user_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último mensaje del cliente'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TRIALING', 'En prueba'), ('ACTIVE', 'Activa'), ('PAST_DUE', 'Pago vencido'), ('CANCELED', 'Cancelada')], default='TRIALING', max_length=20, verbose_name='Estado')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin del trial')),
                ('current_period_start', models.DateTimeField(verbose_name='Inicio del período')),
                ('current_period_end', models.DateTimeField(verbose_name='Fin del período')),
                ('conversations_used', models.PositiveIntegerField(default=0, verbose_name='Conversaciones usadas (período actual)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.plan', verbose_name='Plan')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='orders.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
