# Generated by Django 5.2.8 on 2026-06-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección / ubicación'),
        ),
        migrations.AddField(
            model_name='store',
            name='bot_custom_instructions',
            field=models.TextField(blank=True, default='', help_text="Reglas del dueño. Ej: 'Nunca ofrezcas descuentos', 'Avisa que los viernes hay 2x1'.", verbose_name='Instrucciones para el bot'),
        ),
        migrations.AddField(
            model_name='store',
            name='bot_extra_info',
            field=models.TextField(blank=True, default='', help_text='Promociones, preguntas frecuentes, parqueadero, etc.', verbose_name='Información adicional'),
        ),
        migrations.AddField(
            model_name='store',
            name='bot_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nombre del asistente'),
        ),
        migrations.AddField(
            model_name='store',
            name='bot_personality',
            field=models.TextField(blank=True, default='', help_text='Tono y estilo. Vacío = mesero colombiano carismático por defecto.', verbose_name='Personalidad del bot'),
        ),
        migrations.AddField(
            model_name='store',
            name='business_description',
            field=models.TextField(blank=True, default='', help_text='Qué vende, especialidad, qué lo hace diferente.', verbose_name='Descripción del negocio'),
        ),
        migrations.AddField(
            model_name='store',
            name='business_hours',
            field=models.TextField(blank=True, default='', help_text='Ej: Lun-Vie 11am-10pm, Sáb-Dom 12pm-11pm.', verbose_name='Horarios de atención'),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_info',
            field=models.TextField(blank=True, default='', help_text='Zonas de cobertura, costo del domicilio, tiempos de entrega.', verbose_name='Domicilios'),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_instructions',
            field=models.TextField(blank=True, default='', help_text='Ej: Nequi 3001234567 a nombre de Juan. Se le dictan al cliente cuando elige pagar por transferencia.', verbose_name='Datos de pago manual'),
        ),
    ]
