# Generated by Django 5.2.8 on 2026-06-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_store_address_store_bot_custom_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo domicilio (snapshot)'),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarifa fija de domicilio. 0 = sin costo / domicilio gratis.', max_digits=10, verbose_name='Costo del domicilio'),
        ),
        migrations.AddField(
            model_name='store',
            name='free_delivery_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si el subtotal alcanza este monto, el domicilio es gratis. Vacío = nunca gratis automático.', max_digits=10, null=True, verbose_name='Domicilio gratis desde'),
        ),
        migrations.AlterField(
            model_name='store',
            name='delivery_info',
            field=models.TextField(blank=True, default='', help_text='Zonas de cobertura, tiempos de entrega (texto libre informativo).', verbose_name='Domicilios'),
        ),
    ]
