# Generated by Django 5.2.8 on 2026-06-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_delivery_fee_store_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='prep_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Estimado que el bot le da al cliente que pregunta por su pedido. Ej: 40 → 'estará en ~40 min'. Vacío = el bot no promete tiempo.", null=True, verbose_name='Tiempo de preparación/entrega (min)'),
        ),
    ]
