# Generated by Django 5.2.8 on 2026-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcredentials',
            name='phone_number_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Phone Number ID'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('platform', 'external_id'), name='unique_platform_external_id'),
        ),
    ]
