# Generated by Django 5.2.8 on 2026-07-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_whatsappcredentials_phone_number_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_address',
            field=models.TextField(blank=True, default='', help_text='Última dirección de entrega usada; el bot la ofrece para no re-pedirla', verbose_name='Dirección habitual'),
        ),
    ]
