# Generated by Django 5.2.8 on 2026-07-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_customer_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Instrucciones del cliente para el negocio/domiciliario (las registra el bot)', verbose_name='Notas del pedido'),
        ),
    ]
