# Generated by Django 5.2.8 on 2026-07-09 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('STORE_UPDATE', 'Edición de configuración de tienda'), ('SUBSCRIPTION_CHANGE', 'Cambio de plan/suscripción'), ('IMPERSONATE', 'Inicio de sesión como usuario')], db_index=True, max_length=30)),
                ('store_name', models.CharField(blank=True, default='', max_length=100)),
                ('target_user_email', models.CharField(blank=True, default='', help_text='Usuario impersonado (solo acción IMPERSONATE)', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Diff de campos {campo: {antes, despues}} u otros metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Miembro del equipo')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='orders.store', verbose_name='Tienda afectada')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
