# Generated by Django 5.2.8 on 2026-07-16 05:48

from django.db import migrations, models


def mark_existing_stores(apps, schema_editor):
    # Las tiendas que ya existían no deben ver el wizard de bienvenida.
    Store = apps.get_model('orders', 'Store')
    Store.objects.update(onboarding_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderitem_product_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding completado'),
        ),
        migrations.RunPython(mark_existing_stores, migrations.RunPython.noop),
    ]
