# Generated by Django 5.2.8 on 2026-07-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_store_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Imagen del menú digital'),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_image_source',
            field=models.CharField(blank=True, choices=[('GENERATED', 'Generada desde el menú'), ('UPLOADED', 'Subida por el dueño')], default='', max_length=10, verbose_name='Origen de la imagen del menú'),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_image_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actualización del menú digital'),
        ),
    ]
