# Generated by Django 5.2.8 on 2026-07-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_store_menu_image_store_menu_image_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='menu_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_backgrounds/', verbose_name='Fondo IA del menú digital'),
        ),
    ]
