# Generated by Django 5.2.8 on 2026-08-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_store_menu_bg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Código de confirmación')),
                ('facebook_user_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID de usuario de Facebook')),
                ('requester_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo del solicitante')),
                ('source', models.CharField(choices=[('META_CALLBACK', 'Callback de Meta'), ('USER_REQUEST', 'Solicitud del usuario')], default='USER_REQUEST', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibida'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], db_index=True, default='RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de eliminación de datos',
                'verbose_name_plural': 'Solicitudes de eliminación de datos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappcredentials',
            name='encrypted_pin',
            field=models.TextField(blank=True, default='', verbose_name='PIN de dos pasos (encriptado)'),
        ),
        migrations.AddField(
            model_name='whatsappcredentials',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='App suscrita a los webhooks de la WABA'),
        ),
        migrations.AddField(
            model_name='whatsappcredentials',
            name='verified_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nombre visible aprobado por Meta'),
        ),
    ]
