# Generated by Django 5.2.8 on 2026-08-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_datadeletionrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STORE_UPDATE', 'Edición de configuración de tienda'), ('SUBSCRIPTION_CHANGE', 'Cambio de plan/suscripción'), ('IMPERSONATE', 'Inicio de sesión como usuario'), ('ACCOUNT_DELETION', 'Eliminación de cuenta y datos')], db_index=True, max_length=30),
        ),
    ]
