# Generated by Django 5.2.8 on 2026-08-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STORE_UPDATE', 'Edición de configuración de tienda'), ('SUBSCRIPTION_CHANGE', 'Cambio de plan/suscripción'), ('IMPERSONATE', 'Inicio de sesión como usuario'), ('STAFF_LOGIN', 'Acceso al panel interno'), ('ACCOUNT_DELETION', 'Eliminación de cuenta y datos')], db_index=True, max_length=30),
        ),
    ]
