# Generated by Django 5.2.8 on 2026-08-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_accounttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bot_paused',
            field=models.BooleanField(default=False, help_text='El dueño tomó el control de esta conversación', verbose_name='Bot en pausa'),
        ),
        migrations.AddField(
            model_name='order',
            name='bot_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
