"""
Django settings for whatsapp_orders project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# En dev se permite un fallback inseguro; en producción (DEBUG=False) es OBLIGATORIO
# definir SECRET_KEY por entorno o el arranque falla (evita firmar con clave pública).
_INSECURE_SECRET = 'django-insecure-o!z2^be3a1b^o#rgh(9i9xq-v0llse%gq9$19bo=yw%v_&b41*'
SECRET_KEY = os.getenv('SECRET_KEY', _INSECURE_SECRET)
if not DEBUG and SECRET_KEY == _INSECURE_SECRET:
    raise RuntimeError(
        'SECRET_KEY no definida en producción (DEBUG=False). '
        'Exporta una clave secreta estable en el entorno antes de arrancar.'
    )

# Parse ALLOWED_HOSTS from env, plus add tunnel domains automatically
_allowed = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# Add ngrok domains (free and paid) to allow tunnel access
_allowed.extend(['.ngrok-free.app', '.ngrok.io', '.ngrok-free.dev'])
# Dominio de producción. En el repo privado aquí también va el dominio del
# túnel de desarrollo; omitido en este snapshot público.
_allowed.extend(['.dilo.example.com', 'dilo.example.com'])
ALLOWED_HOSTS = _allowed


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'orders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'whatsapp_orders.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'whatsapp_orders.wsgi.application'
ASGI_APPLICATION = 'whatsapp_orders.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

db_engine = os.getenv('DB_ENGINE', '').strip().lower()
db_host = os.getenv('DB_HOST', '').strip()
db_name = os.getenv('DB_NAME', '').strip()
db_user = os.getenv('DB_USER', '').strip()

use_postgres = False
if db_engine in {'postgres', 'postgresql', 'psql'}:
    use_postgres = True
elif db_engine in {'sqlite', 'sqlite3'}:
    use_postgres = False
elif db_host and db_user != 'your_db_user' and db_name != 'your_db_name':
    # Avoid forcing PostgreSQL when .env still has template placeholders.
    use_postgres = True

if use_postgres:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': db_name or 'dilo',
            'USER': db_user or 'dilo',
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': db_host,
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Channels configuration
# REDIS_URL (redis://:pass@host:port/0) tiene prioridad — necesario en prod
# donde el Redis lleva password (la tupla host/port no autentica).
_channels_redis = os.getenv('REDIS_URL') or (
    os.getenv('REDIS_HOST', '127.0.0.1'),
    int(os.getenv('REDIS_PORT', 6379)),
)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [_channels_redis],
        },
    },
}


# WhatsApp Configuration
WHATSAPP_API_TOKEN = os.getenv('WHATSAPP_API_TOKEN')
WHATSAPP_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID')
WHATSAPP_VERIFY_TOKEN = os.getenv('WHATSAPP_VERIFY_TOKEN')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')

# Meta App (Embedded Signup de WhatsApp) — credenciales a nivel plataforma.
# Se obtienen creando una App en developers.facebook.com con el producto WhatsApp.
META_APP_ID = os.getenv('META_APP_ID')
META_APP_SECRET = os.getenv('META_APP_SECRET')


# AI Configuration
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY')
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
# Google Gemini API directa (Google AI Studio / generativelanguage). Se usa vía
# el endpoint compatible con OpenAI, así el mismo cliente OpenAI-SDK sirve.
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')

# AI Model Selection
# Providers: 'openai', 'deepseek', 'anthropic', 'openrouter', 'gemini'
# Models: 'gpt-4o-mini', 'deepseek-chat', 'claude-3-5-sonnet-20241022', 'gemini-2.5-flash'
AI_PROVIDER = os.getenv('AI_PROVIDER', 'gemini')
AI_MODEL = os.getenv('AI_MODEL', 'gemini-2.5-flash')
# Modelo con visión (lee fotos de menú). gemini-2.5-flash es multimodal nativo.
AI_VISION_MODEL = os.getenv('AI_VISION_MODEL', 'gemini-2.5-flash')
# Modelo de GENERACIÓN de imagen (fondo decorativo del menú digital, sin
# texto). Debe soportar salida de imagen vía chat completions en OpenRouter
# (modalities: image). OJO: openai/gpt-image-1-mini NO — OpenRouter responde
# 404 "No endpoints found that support the requested output modalities".
AI_IMAGE_MODEL = os.getenv('AI_IMAGE_MODEL', 'google/gemini-2.5-flash-image')

# Google Vision API — validación de confianza del menú por foto (TEXT_DETECTION
# antes de gastar tokens del LLM). Vacío = validación deshabilitada (fail-open).
GOOGLE_VISION_API_KEY = os.getenv('GOOGLE_VISION_API_KEY', '')

# Google Sign-In (OAuth) — Client ID del cliente web creado en Google Cloud
# Console (Google Auth Platform → Clientes). Vacío = login con Google apagado
# (el endpoint responde 503). El mismo ID va en el frontend como
# REACT_APP_GOOGLE_CLIENT_ID.
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')


# Frontend URL (para redirects de pago)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# URL pública del backend (para registrar webhooks externos como Telegram).
# En dev con túnel Cloudflare apunta al dominio público; en prod al backend.
BACKEND_PUBLIC_URL = os.getenv('BACKEND_PUBLIC_URL', 'https://dilo.example.com')

# Recompra automática (win-back): re-contacta clientes inactivos.
WINBACK_DAYS = int(os.getenv('WINBACK_DAYS', '14'))          # días sin pedir para reactivar
WINBACK_COOLDOWN_DAYS = int(os.getenv('WINBACK_COOLDOWN_DAYS', '14'))  # no re-contactar antes de N días
# OJO WhatsApp: fuera de la ventana de 24h SOLO se puede iniciar con plantilla
# aprobada por Meta. Telegram no tiene esa restricción.
WHATSAPP_WINBACK_TEMPLATE = os.getenv('WHATSAPP_WINBACK_TEMPLATE', '')  # nombre de plantilla aprobada

# Billing (suscripciones DILO): trial inicial y ventana de conversación facturable.
TRIAL_DAYS = int(os.getenv('TRIAL_DAYS', '14'))
CONVERSATION_WINDOW_HOURS = int(os.getenv('CONVERSATION_WINDOW_HOURS', '24'))

# Minutos que dura la toma de control humana antes de que el bot vuelva solo.
BOT_PAUSE_MINUTES = int(os.getenv('BOT_PAUSE_MINUTES', '60'))



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Hora de Colombia, no UTC. Con `USE_TZ=True` la DB sigue guardando todo en UTC
# (no cambia un solo dato); lo que cambia es lo que LEE una persona:
# `timezone.localtime()` en los correos de seguridad, el admin de Django y los
# horarios del beat. Con 'UTC' un aviso de "iniciaste sesión a las 12:34 p. m."
# le llegaba al dueño a las 7:34 a. m. — la hora equivocada en un correo de
# seguridad hace que el usuario crea que lo hackearon.
TIME_ZONE = os.getenv('TIME_ZONE', 'America/Bogota')

USE_I18N = True

USE_TZ = True

# Celery NO hereda el TIME_ZONE de Django (su default es UTC pase lo que pase):
# hay que decírselo explícito o el `crontab(hour=15)` del win-back corre a las
# 10 a. m. hora de Bogotá, no a las 3 p. m. como dice su comentario.
CELERY_TIMEZONE = TIME_ZONE


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Celery Configuration
_redis_host = os.getenv('REDIS_HOST', '127.0.0.1')
_redis_port = os.getenv('REDIS_PORT', '6379')
_default_redis_url = os.getenv('REDIS_URL') or f'redis://{_redis_host}:{_redis_port}/0'
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', _default_redis_url)
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', _default_redis_url)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Bogota'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos máximo por tarea


# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Throttling: protege endpoints públicos/costosos (OTP, menú por foto) del abuso.
    # Scopes específicos se aplican por vista con ScopedRateThrottle.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_ANON', '60/min'),
        'user': os.getenv('THROTTLE_USER', '600/min'),
        'otp': os.getenv('THROTTLE_OTP', '5/min'),        # registro/login OTP
        'menu_extract': os.getenv('THROTTLE_MENU', '10/min'),  # IA visión (cara)
        # Puerta del panel interno: fuerza bruta contra el super admin
        'staff_login': os.getenv('THROTTLE_STAFF_LOGIN', '5/min'),
        # Canje del código que llega por correo (2º paso del panel)
        'staff_mfa': os.getenv('THROTTLE_STAFF_MFA', '10/min'),
        # Enlaces de un solo uso de la cuenta (reset de contraseña / cambio de
        # correo): son un vector de spam hacia buzones ajenos, no solo de
        # fuerza bruta.
        'account_action': os.getenv('THROTTLE_ACCOUNT_ACTION', '5/min'),
    },
}


# Simple JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


CSRF_TRUSTED_ORIGINS = [
    'https://dilo.example.com',
    'https://app.dilo.example.com',
]

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
    'https://dilo.example.com',
    'https://app.dilo.example.com',
]

CORS_ALLOW_CREDENTIALS = True


# ---------------------------------------------------------------------------
# Hardening de producción (solo cuando DEBUG=False).
# En dev se omite para no romper http://localhost ni el túnel.
# ---------------------------------------------------------------------------
if not DEBUG:
    # HTTPS / redirección. El proxy (nginx/PaaS) termina TLS y manda el header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True').lower() == 'true'

    # HSTS — fuerza HTTPS en el navegador (1 año + subdominios).
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies solo por HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Endurecimiento de cabeceras.
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'


# ---------------------------------------------------------------------------
# Observabilidad — Sentry (opcional, se activa con SENTRY_DSN en el entorno).
# ---------------------------------------------------------------------------
SENTRY_DSN = os.getenv('SENTRY_DSN', '').strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.celery import CeleryIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration(), CeleryIntegration()],
            traces_sample_rate=float(os.getenv('SENTRY_TRACES_RATE', '0.1')),
            send_default_pii=False,
            environment=os.getenv('SENTRY_ENV', 'production' if not DEBUG else 'development'),
        )
    except ImportError:
        import logging as _logging
        _logging.getLogger(__name__).warning(
            'SENTRY_DSN definido pero sentry-sdk no instalado. pip install sentry-sdk[django]'
        )


# ---------------------------------------------------------------------------
# Correo saliente (SMTP) — hoy solo lo usa el codigo de verificacion del panel
# interno (/admin/login). El proveedor real se configura por entorno.
#
# Puerto 465 = SSL implicito; 587 = STARTTLS. Se deduce del puerto para no
# depender de dos flags que se contradicen entre si.
#
# Sin EMAIL_HOST_PASSWORD el backend cae a consola: en dev el codigo se
# imprime en el log en vez de fallar el login del panel.
# ---------------------------------------------------------------------------
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '465'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'hola@example.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_SSL = EMAIL_PORT == 465
EMAIL_USE_TLS = EMAIL_PORT in (587, 25)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '15'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', f'DILO <{EMAIL_HOST_USER}>')

EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_PASSWORD
    else 'django.core.mail.backends.console.EmailBackend'
)


# ---------------------------------------------------------------------------
# Panel interno (/admin) — quien puede entrar y con que sesion.
# ---------------------------------------------------------------------------
# Solo cuentas de estos dominios son equipo interno. Una cuenta con rol
# dilo_* en cualquier otro dominio queda fuera del panel completo, no solo
# del login (ver staff_permissions.staff_role).
STAFF_EMAIL_DOMAINS = [
    d.strip().lower().lstrip('@')
    for d in os.getenv('STAFF_EMAIL_DOMAINS', 'dilo.example.com').split(',')
    if d.strip()
]
# Vida del codigo de verificacion que se envia por correo al entrar al panel.
STAFF_MFA_CODE_TTL_SECONDS = int(os.getenv('STAFF_MFA_CODE_TTL', '180'))
# Intentos de codigo por desafio antes de invalidarlo (fuerza bruta de 6 digitos).
STAFF_MFA_MAX_ATTEMPTS = int(os.getenv('STAFF_MFA_MAX_ATTEMPTS', '5'))


# ---------------------------------------------------------------------------
# Acciones sensibles de la cuenta del comercio (enlaces de un solo uso).
# ---------------------------------------------------------------------------
# Enlace para crear contrasena nueva. Corto a proposito: el correo del usuario
# puede quedar abierto en un equipo compartido.
PASSWORD_RESET_TTL_MINUTES = int(os.getenv('PASSWORD_RESET_TTL_MINUTES', '60'))
# Enlace para confirmar un correo nuevo. Mas largo porque el usuario tiene que
# ir a revisar OTRO buzon, que quiza no tenga a mano.
EMAIL_CHANGE_TTL_MINUTES = int(os.getenv('EMAIL_CHANGE_TTL_MINUTES', '120'))
